### ISSUE TITLE
create standup (lita-wizard) only works properly when talking privately with the bot

### ISSUE THREAD

**Issue by spkane** [cristianbica/lita-standups#6]
If you run `create standup` in a room lita-wizard does not work properly, but this is not documented or handled properly by the plugin.

If lita-wizard can't easily be made to work in a room (understandably), then it would be good to allow people to run `create standup` from a room, but then to send them a private message from the bot initiating the communications.

**Comment by cristianbica** [comment]
It seems it's a bug in lita-wizard. When starting a wizard in a room it write the initial text and first question in the room but it's expecting an answer in the private channel. Will handle this on lita-wizard side https://github.com/cristianbica/lita-wizard/issues/3

**Comment by spkane** [comment]
see: https://github.com/cristianbica/lita-wizard/pull/4

**Comment by cristianbica** [comment]
Fixed by https://github.com/cristianbica/lita-wizard/pull/4. Released as [v1.0.3](https://github.com/cristianbica/lita-wizard/releases/tag/v1.0.3)
